# Generated by Django 4.2.4 on 2023-09-10 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_customer_order_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='Customer',
        ),
    ]
